export const LOADING = 'LOADING';
export const SET_ERROR = 'SET_ERROR';

export const GET_CRYPTOS = 'GET_CRYPTOS';
export const GET_CRYPTOS_SUCCESS = 'GET_CRYPTOS_SUCCESS';
export const GET_CRYPTOS_ERROR = 'GET_CRYPTOS_ERROR';

export const SET_SELECTED_CRYPTO = 'SET_SELECTED_CRYPTO';
